title: Tomas Jasovsky
email: hello@dusko.sk
description: Hello, my name is Tomas Jasovsky. I’m a Product Designer looking for a fish to fry!
facebook: facebook_tddfc9
favicon: favicon_sqw9yp

# build settings
markdown: kramdown
