title: Tomas Jasovsky
email: hello@dusko.sk
description: Hello, my name is Tomas Jasovsky. I’m a Product Designer looking for a fish to fry!
baseurl: ""
url: "http://yourdomain.com"

# build settings
markdown: kramdown
